/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>

export interface Favorite {
  id: Generated<number>
  recipe_id: number
  user_id: number
}

export interface Ingredient {
  amount: string
  id: Generated<number>
  name: string
  recipe_id: number
}

export interface Like {
  created_at: Generated<string>
  family_id: number | null
  id: Generated<number>
  recipe_id: number
  user_id: number
}

export interface Recipe {
  author_id: number
  cover: string | null
  created_at: Generated<string>
  description: string | null
  id: Generated<number>
  instructions: string | null
  likes: Generated<number>
  name: string
  source: string | null
}

export interface RecipeTag {
  recipe_id: number
  tag_id: number
}

export interface Tag {
  filter_id: number
  id: Generated<number>
  name: string
}

export interface User {
  created_at: Generated<string>
  email: string
  family_id: number | null
  id: Generated<number>
  login_hash: string | null
  name: string
}

export interface DB {
  favorite: Favorite
  ingredient: Ingredient
  like: Like
  recipe: Recipe
  recipe_tag: RecipeTag
  tag: Tag
  user: User
}
